# Generated by Django 4.2.16 on 2025-11-20 14:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('summary', models.JSONField()),
                ('user_id', models.CharField(blank=True, max_length=36, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
    ]
